### ISSUE TITLE
RegisterAdditionalFileWatchersForSymLinkDirs throws error

### ISSUE THREAD

**Issue by PhantomGamers** [d2phap/filewatcher-windows#15]
I just received this error log from a user of my application which utilizes FileWatcherEx:

```
System.UnauthorizedAccessException: Access to the path 'c:\program files (x86)\steam\steamapps\common\wallpaper_engine\ui\uicache\welcome\user\WidevineCdm\4.10.2391.0' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String, Boolean )
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String, FindTransform, EnumerationOptions, Boolean)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String, String, EnumerationOptions, Boolean)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String, String, SearchTarget, EnumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories(String, EnumerationOptions)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at SFP.Models.Steam.StartMonitorSteam() in C:\Users\Phantom\Documents\GitHub\SFP\SFP\Models\Steam.cs:line 188
```

[SFP.Models.Steam.StartMonitorSteam() can be found here](https://github.com/PhantomGamers/SFP/blob/6f0800e38f5b3ca02e685ab1923d59a1f4272432/SFP/Models/Steam.cs#L174-L187)

My application creates a new FileSystemWatcherEx instance with the given path in this case being `c:\program files (x86)\steam`, I do not have IncludeSubdirectories set to true for this instance so why does `RegisterAdditionalFileWatchersForSymLinkDirs` run on all sub-directories of this folder?

I'm not sure if this is a bug or if there is some reason for this functionality, but if it is intended to go through all subdirectories like this then I think there needs to be a try catch implemented because there can be cases where the user has permissions for the base folder but not to certain subdirectories in that base folder.

**Comment by PhantomGamers** [comment]
To add onto this, I'm doing some testing on Linux and it seems to be an even bigger issue when there are cyclical symlinks (symlinks that contain symlinks pointing back to themselves) in a directory.

```
System.IO.IOException: Too many levels of symbolic links : '/home/pgamers/.steam/steam/ubuntu12_32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/bin32/ubuntu12_32/ubuntu12_32/bin32/bin32/bin32/ubuntu12_32/steam-runtime.old/amd64/usr/libexec/steam-runtime-tools-0/x86_64-linux-gnu/haswell'
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String, Boolean )
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String, String, EnumerationOptions, Boolean)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String, String, SearchTarget, EnumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories()
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   + 28 more RegisterAdditionalFileWatchersForSymLinkDirs calls
```

Sometimes it fails and errors out like this, other times it runs indefinitely until the program is exited without a crash but without ever succeeding. Not sure what causes it to crash vs hang, it seems to change run to run without any changes to the environment.

I suppose this is a separate but related issue since this should be handled better in cases where `IncludeSubdirectories` is true as well.
